export const SET_USER = 'SET_USER'
export const SET_OAUTH_TOKEN = 'SET_OAUTH_TOKEN'
export const SET_OAUTH_TOKEN_SECRET = 'SET_OAUTH_TOKEN_SECRET'
export const SET_TWEETS = 'SET_TWEETS'
export const LOGOUT = 'LOGOUT'
